### PR TITLE
fix: remove reliance on top level await and external polyfill/helper

### LINKED ISSUE #32: bug: use of top level awaits and node modules causes bunding errors
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Version (i.e. v2.x.x)

All

### Node.js version (i.e. 18.x, or N/A)

_No response_

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10, or N/A)

_No response_

### Description

There are a number of issues when trying to use this polyfill with various bundlers. In particular, top level awaits related to dynamically importing other modules and Node dependencies create issues. I believe these can be easily resolved by simplifying the two places that cause the problem:

* `util/uuid-or-random.ts` - Remove `node:crypto`. I'm not sure you need a cryptographically random number in your scenarios. Just use the fake v4 implementation or something similar.
* `util/structured.json` - This appears to only be using basic parsing and stringification, not structured cloning. Remove this and just use built-in JSON APIs directly.

These changes fix the errors and will reduce code size and complexity. **I'm happy to make a PR with the proposed changes if you are interested.** As it stands, this poyfill does not work with esbuild or any build systems based on esbuild.

### Steps to Reproduce

* Setup a basic ES6 browser build with esbuild.
* Import the polyfill in your index.js
* Attempt to build

### Expected Behavior

I would expect to be able to bundle without any errors.

### PR DESCRIPTION
**Pull request by EisenbergEffect**
This PR reworks the serialization code to use `JSON.stringify` and `JSON.parse` instead of structured clone and a third-party serialization polyfill/helper. A new function called `configureSerialization(...)` has been added to provide developers with a way to plug back in the more advanced serialization approach if they want/need it for their app.

#### Checklist

- [x] run `yarn build`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/virtualstate/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/virtualstate/.github/blob/master/CODE_OF_CONDUCT.md)

#### Issues

* Fixes #32 

#### Notes

A couple of critical things are left undone. I'm looking for some help/feedback on:

* I am still unable to run the build on Windows out-of-the-box, so I didn't verify by running the build or tests. We'll see what happens with CI.
* I didn't make changes to the custom build scripts for rollup, etc. There was a lot of code there and I'm not very familiar with custom rollup solutions in general. Perhaps someone else can remove the vestiges of the old polyfill system that are still there.
* Please let me know where you want me to document `configureSerialization(...)` and I'll amend this PR with that (assuming you support the approach I took).

### CODE REVIEW

**Comment by fabiancook** [comment]
Beyond the rollup issue, were you having any specific issues with windows? I checked through the scripts and they are all node based for this project, so should be okay.

**Comment by fabiancook** [comment]
Also having a think about the serializer, its reasonable to configure a serialiser. I've updated the code slightly so that a single object can be passed for it. Being able to use JSON by default will be a lot cleaner upfront. 

If someone needs a complex state serializer, they can with no concern now.

**Comment by fabiancook** [comment]
I have released this as 1.0.1-alpha.206

**Comment by EisenbergEffect** [comment]
Awesome! Thank you @fabiancook !

**Pull request merged**
